### ISSUE TITLE
unify chgres namelist for ICS

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#44]

**Comment by ShunLiu-NOAA** [comment]
![image](https://user-images.githubusercontent.com/8901479/133107278-6d684ab0-6c17-42dc-bbbb-b440a0cf0224.png)
![image](https://user-images.githubusercontent.com/8901479/133112012-9e0928a2-1887-4e5a-86f5-dd37997f5da4.png)

I compared the input namelist of chgres for generating ICS used between EMC and GSL, there are a few differences.  Is it possible that we use the unified namelist and minimize the difference?

**Comment by ShunLiu-NOAA** [comment]
namelist files used at EMC and GSL are in /gpfs/dell2/emc/modeling/save/Shun.Liu/rrfs/unified_chgres_namelist

**Comment by EricRogers-NOAA** [comment]
In principle I have no problem with this. But I'm wondering about the difference in the convert_nst settings. My understanding is that it's supposed to be set to be true when chgres_cube reads in the atmf netcdf file when the DA is coldstarted, because we have no outside source of SST other than what we get from the GDAS. Is the namelist you show on the right from GSL? If so I'd like to knoe why they have convert_nst set to false.

**Comment by ShunLiu-NOAA** [comment]
Ming,

Could you confirm if you are using "convert_nst=.false." in GSL's test? Are
any other parameters caused the difference in ICS?

Thanks.

Shun

**Comment by hu5970** [comment]
We should check if "convert_nst=.false." is good one to use in GSL side. I guess we never pay enough attention to this one.

Thanks,
Ming

**Comment by ShunLiu-NOAA** [comment]
Compare ICs between EMC-RRFS and EMC-FV3LAMDA.
1. use GDAS netcdf to generate ICs
2. use the same executable as EMC-FV3LAMDA.
